spring.application.name=task_test_work

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5433/task_db}
spring.datasource.username=${DB_USER:postgres}
spring.datasource.password=${DB_PASSWORD:1}